import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/layouts/MainLayout";
import Header from "@/components/header/Header";
import NavigationBar from "@/components/navigation-bar/NavigationBar";
import Player from "@/components/player/Player";
import { Suspense } from "react";
import { ErrorBoundary } from "react-error-boundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-lvh">
        <MainLayout
          header={<Header onClick={() => console.log("click")} />}
          navigation={<NavigationBar />}
          player={<Player />}
          content={
            <ErrorBoundary fallback={<div>Error Boundary</div>}>
              <Suspense fallback={"...loading"}>{children}</Suspense>
            </ErrorBoundary>
          }
        />
      </body>
    </html>
  );
}
